spring:
  datasource:
    url: jdbc:mysql://rm-uf65wgf088nv3k461oo.mysql.rds.aliyuncs.com:3306/bmsys?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: ld
    password: Ld1213+@
    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    rest:
      uris: http://172.28.200.85:9200
      read-timeout: 30s
      connection-timeout: 5s

fdfs:
  so-timeout: 1000
  connect-timeout: 1000
  tracker-list:
    - 192.168.0.103:22122
  pool:
    max-total: 50 #连接池最大连接数50
    test-while-idle: true
    block-when-exhausted: true #当缓存池耗尽是否阻塞，默认为true  false直接报异常，true阻塞直到超时
    max-wait-millis: 1000 #连接耗尽最大等待时间 毫秒，超时抛出异常
    min-evictable-idle-time-millis: 18000 #休眠时间超过该值则视为过期时间
    time-between-eviction-runs-millis: 6000 #60秒进行一次后台清理
    num-tests-per-eviction-run: -1 #清理时检查所有线程
